import os

class Config:
    SAMPLE_RATE = 16000
    CHANNELS = 1
    SAMPLE_WIDTH = 2
    FRAME_DURATION_MS = 30
    PADDING_DURATION_MS = 300
    VAD_AGGRESSIVENESS = 1
    MAX_CHUNK_DURATION_MS = 60000
    MAX_SUMMARY_CHUNK_SIZE = 4000